title: LaByte
subtitle: "Messing Bits"
description: "Messy Bits"
keywords: null
author: Thuri
language: en
timezone: ""

# Set Site URl
url: http://thuri10.github.io
permalink: ":year/:month/:day/:title/"
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ":lang"
skip_render: null
new_post_name: ":title.md"
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ""
index_generator:
  path: ""
  per_page: 8
  order_by: "-date"
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true

#Date and Time Format
date_format: MMMM DD Y
time_format: HH:mm:ss
updated_option: mtime

# Paginations of blogs per page
per_page: 8
pagination_dir: page
include: null
exclude: null
ignore: null
theme: next
deploy:
  type: git
  repo: git@github.com:thuri10/thuri10.github.io.git
  branch: master
